version: "3.7"

services:
  db-mysql:
    platform: linux/x86_64
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: musinsa
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge